- name: Obtener github.com/molavec/git-tools
  git:
    repo: https://github.com/molavec/git-tools.git
    dest: ~/git/tools/git-tools
    remote: origin-https
  notify:
    - 'symlink gitattributesgen to ~/bin'
    - 'symlink gitignoregen to ~/bin'

- name: Setup default git configuraiton
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "{{ git_user_name }}" }
    - {name: "user.email", value: "{{ git_user_email }}" }
    - {name: "ui.color",   value: "{{ git_ui_color }}" }
    - {name: "core.editor",   value: "{{ git_core_editor }}" }
