- name: Obtener github.com/molavec/git-tools
  git:
    repo: https://github.com/molavec/git-tools.git
    dest: ~/git/tools/git-tools
    remote: origin-https
  notify:
    - 'symlink gitattributesgen to ~/bin'
    - 'symlink gitignoregen to ~/bin'
