- name: set node_modules prefix
  ansible.builtin.command: 
    argv:
      - npm
      - config
      - set
      - prefix
      - $HOME/.npm/node_modules

- name: set npm_cache
  ansible.builtin.command: 
    argv:
      - npm
      - config
      - set
      - cache
      - $HOME/.npm/npm_cache

- name: set global bin in zshrc
  ansible.builtin.command:
    cmd: echo '# binarios de node_modules \n[[ -d ~/.npm/node_modules/ ]] && path=("$HOME/.npm/node_modules/bin" $path)\n'
    stdin: $HOME/.zshrc
    stdin_add_newline: yes
